@baseUrl = http://127.0.0.1:5000
@contentType = application/json

### 1. Registrasi Pengguna Baru
POST {{baseUrl}}/auth/register
Content-Type: {{contentType}}

{
    "email": "user_test_01@example.com",
    "password": "password_rahasia_123"
}

### 2. Login (Dapatkan Token JWT)
# @name login
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
    "email": "user_test_01@example.com",
    "password": "password_rahasia_123"
}

###
# --- VARIABEL TOKEN OTOMATIS ---
# Baris di bawah ini mengambil token dari response request 'login' di atas.
# Pastikan kamu menjalankan request Login terlebih dahulu!
@authToken = {{login.response.body.access_token}}


### 3. Cek Profil / History (Tes Token)
GET {{baseUrl}}/api/history
Authorization: Bearer {{authToken}}


### 4. Upload Audio (Memicu Celery Worker)
# Note: Pastikan path file '< ./...' benar relatif terhadap file .http ini
POST {{baseUrl}}/api/analysis/audio
Authorization: Bearer {{authToken}}
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="file"; filename="test_suara.mp3"
Content-Type: audio/mpeg

< ./celery_worker/assets/test.mp3
--MyBoundary--


### 5. Cek Status Analisis (Polling)
# Ganti ID di bawah secara manual dengan 'analysis_id' dari response Step 4
@analysisId = 32d6d915-b3d5-46f3-994a-a0cc056a816f

GET {{baseUrl}}/api/analysis/{{analysisId}}
Authorization: Bearer {{authToken}}