@baseUrl = http://127.0.0.1:5000
@contentType = application/json

# Variabel untuk menyimpan token (VS Code REST Client mendukung @name)
# Ganti token manual di bawah jika variabel tidak jalan di versi extension Anda.

### 1. Registrasi Pengguna Baru
POST {{baseUrl}}/auth/register
Content-Type: {{contentType}}

{
    "email": "user_test_01@example.com",
    "password": "password_rahasia_123"
}

### 2. Login (Dapatkan Token JWT)

# @name login
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
    "email": "user_test_01@example.com",
    "password": "password_rahasia_123"
}

@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc2NDA2MDU5MiwianRpIjoiYzdkMDBkNjUtNTc1ZS00NWU4LTk4MzItNGQzZDAxNmVhYWQ0IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6ImFlOTlmZDY0LWUyZDAtNDJiZC1iOWQzLThkODQ3MzhkMTQ4OSIsIm5iZiI6MTc2NDA2MDU5MiwiY3NyZiI6IjMxZDY5ZDc4LWFmNDktNDY2ZS1hOTIzLTliNmJiMzA0YWI2NSIsImV4cCI6MTc2NDA2MTQ5Mn0.N_D95X9Z5cqzPIekev0IfomYHaBFd8poTYti3QRCt7s


### 3. Cek Profil / History (Tes Token)
GET {{baseUrl}}/api/history
Authorization: Bearer {{authToken}}

### 4. Upload Audio (Memicu Celery Worker)
POST {{baseUrl}}/api/analysis/audio
Authorization: Bearer {{authToken}}
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="file"; filename="test_suara.mp3"
Content-Type: audio/mpeg

< ./celery_worker/assets/test.mp3
--MyBoundary--


### 5. Cek Status Analisis (Polling)
# Ganti ID di bawah dengan 'analysis_id' yang Anda dapat dari respons Upload
@analysisId = a8fbb6bc-bc36-4838-833c-2e706bda3ea9

GET {{baseUrl}}/api/analysis/{{analysisId}}
Authorization: Bearer {{authToken}}